// Common iOS bundle ids and Apple system screens to display names; a miss
// falls to the App Store lookup. `com.burbn.instagram` and
// `xyz.blueskyweb.app` stay out so the lookup path runs for them.
export const iosAppNames: Record<string, string> = {
  "com.apple.mobilesafari": "Safari",
  "com.apple.mobilenotes": "Notes",
  "com.apple.mobilemail": "Mail",
  "com.apple.MobileSMS": "Messages",
  "com.apple.mobilecal": "Calendar",
  "com.apple.Maps": "Maps",
  "com.apple.mobileslideshow": "Photos",
  "com.apple.mobilecamera": "Camera",
  "com.apple.weather": "Weather",
  "com.apple.stocks": "Stocks",
  "com.apple.reminders": "Reminders",
  "com.apple.AppStore": "App Store",
  "com.apple.Preferences": "Settings",
  "com.apple.Music": "Music",
  "com.apple.podcasts": "Podcasts",
  "com.apple.iBooks": "Books",
  "com.apple.DocumentsApp": "Files",
  "com.apple.MobileAddressBook": "Contacts",
  "com.apple.facetime": "FaceTime",
  "com.apple.Health": "Health",
  "com.apple.Passbook": "Wallet",
  "com.apple.Home": "Home",
  "com.apple.news": "News",
  "com.apple.freeform": "Freeform",
  "com.apple.journal": "Journal",
  "com.apple.findmy": "Find My",
  "com.apple.shortcuts": "Shortcuts",
  "com.apple.VoiceMemos": "Voice Memos",
  "com.apple.calculator": "Calculator",
  "com.apple.compass": "Compass",
  "com.apple.measure": "Measure",
  "com.apple.Translate": "Translate",
  "com.apple.Keynote": "Keynote",
  "com.apple.Pages": "Pages",
  "com.apple.Numbers": "Numbers",
  "com.apple.garageband": "GarageBand",
  "com.apple.iMovie": "iMovie",
  "com.apple.clips": "Clips",
  "com.apple.tips": "Tips",
  "com.spotify.client": "Spotify",
  "com.netflix.Netflix": "Netflix",
  "com.google.ios.youtube": "YouTube",
  "com.google.Maps": "Google Maps",
  "com.google.Gmail": "Gmail",
  "com.zhiliaoapp.musically": "TikTok",
  "com.facebook.Facebook": "Facebook",
  "com.whatsapp.WhatsApp": "WhatsApp",
  "com.toyopagroup.picaboo": "Snapchat",
  "com.reddit.Reddit": "Reddit",
  "com.linkedin.LinkedIn": "LinkedIn",
  "com.discord.Discord": "Discord",
  "com.slack.Slack": "Slack",
  "com.notion.id": "Notion",
  "com.openai.chat": "ChatGPT",
  "com.duolingo.Duolingo": "Duolingo",
  "com.strava.stravaride": "Strava",
  "com.amazon.Amazon": "Amazon",
  "com.ubercab.UberClient": "Uber",
  // Apple system screens with no App Store entry.
  "com.apple.InCallService": "Phone call",
  "com.apple.LocalAuthenticationUIService": "Face ID & passcode",
  "com.apple.AppProtectionUIHost": "Hidden & locked apps",
  "com.apple.AuthKitUIService": "Apple Account sign-in",
  "com.apple.AuthenticationServicesUI": "Sign-in sheet",
  "com.apple.ServicesPaymentAngel": "App Store purchase",
  "com.apple.PassbookUIService": "Wallet & Apple Pay",
  "com.apple.CTNotifyUIService": "Carrier message",
  "com.apple.HeadphoneProxService": "Headphone connection",
  "com.apple.PosterBoard": "Lock Screen & wallpaper",
  "com.apple.ScreenshotServicesService": "Screenshot",
  "com.apple.purplebuddy": "Setup Assistant",
  "com.apple.webapp": "Web app",
  "com.apple.CoreAuthUI": "Passcode",
  "com.apple.WebSheet": "Wi-Fi login",
  "com.apple.SafariViewService": "In-app Safari",
  "com.apple.PhotosUIService": "Photos picker",
};
